name: "Codesniffer"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  codesniffer:
    name: "Codesniffer"
    uses: contributte/.github/.github/workflows/codesniffer.yml@master
    with:
      php: "8.2"
