name: "Nette Tester"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test82:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
      php: "8.2"

  test81:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
      php: "8.1"

  test80:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
        php: "8.0"

  test74:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
        php: "7.4"

  test73:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
        php: "7.3"
        composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"

  test72:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@v1
    with:
        php: "7.2"
        composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
